### ISSUE TITLE
When in Intel Torch coming out?

### ISSUE THREAD

**Issue by campbx** [xhzhao/Intel-Torch#1]
Hi Mr. Zhao,

Any ETA on the Intel Torch release date?

I also noticed the Colfax research team was able to get a 6x performance multiple in their tweaking of Torch: hope this can help you in tweaking the Intel Torch package further.  
http://colfaxresearch.com/isc16-neuraltalk/

Thank you for your work!

**Comment by xhzhao** [comment]
@campbx Thanks for your reminder, we are reading the colfax research torch source code. This repo is still in performance tuning, as an develop repo. And we will merge to official repo after the performance tuning done.

**Comment by campbx** [comment]
Looking forward to trying it out!  Thank you for the update.

**Comment by campbx** [comment]
Colfax just posted the code on Github as well:

[Colfax Torch](https://github.com/ColfaxResearch/torch7)
